sudo: required

services:
- docker

language: java
jdk:
- oraclejdk8

env:
  global:
  - COMMIT: "${TRAVIS_COMMIT::6}"
  - secure: gsxKidrIQoOkiVOhiAtIynQvV87tApAf0FIeymvRhExdNPbjn7perqtDu3KTRfFfdCGZ5GBtXFSsr89repQU4ExCK/5uvSDVsTikSSShef6XMnHi3OufCq4jsGLF2SRfXkgsoY7RtyTKjiMCa3SwirwEMwG02lgp/Jei8J3OmGjy/60CTQaI5tkQd46UvTpcUDl44Cj+3WHCNgcuqIEvRByAN/uptwf0edjrtQb+JpHvyY7RNHrs7cYVRZvREfSjVy5v0oJolaalSROiD6rwKfI0INUIRI8P1vZZurdh+8BH2TkEXDT8ET6S1lquj9q17QfehIkKqCa9vEsdw5DcLXz6cn3d6Jbwbkt1YpIcVkJ05rDNAUbon06pxTUL/ZaiyRhUG1XbAu5MfxkPtUBzyS66n4Jdp2F/QdtJelDRgC8POlmdqjJKKHC8wwdh0XYh7jXu61lOsTYjMlyInYHEoGfOZRpS1nOZiEkqCE16RY9J0gfSZzkyRLPJY5wcEPlgaoeRzct+nZgk6R2YMAmD9TYdrYTdNibglFV+3cj6FrUC8HtFWf+Enk4de8pUIsp6HsiI0+Jo9g8kOpUAvGGkHhpvHE+J2FRqkBKAVPiBTJdLsYE5cuNnA77GhChZXKuBZshYSjCtg78cjO8aHUadCI053i5faoNSLhfUw9o3Niw=
  - secure: b5zybPtfvNpdwkch2UrzrLOwIG1aVdiM/INLIPLqSsjUAicNLNwodKHsHK3SgbGVxk19APmhQUqh2q4GbPqQ1vb8bFpV80XIEmHGvwDaVbQVrt71nJXkgOoSb4/1Uu3NYc5oGiSQY4Ncop+ztxiupKwPjrDTeeHBh02P/R7E7IibEWkvr77EHP2dCsm+Z4CD4nLHDTuCJYpU1T4tx2DPLuwBM9VGNQAFvURVZt5BonPLxofS7laZWybYPXXun+ZJi0taFgR+CULsqjJyGsSMzXaD/ef2p882fzuplnxALM/qOLxJTmkvBAURusxu51s18dWtrNUWxF4ZEIJ1mpjJH9qS6LJtSREDFhJ+fpQ5GDQ5hnWSAj3Pzs4hT6a0IdwULCQ8zNO187ek6Gg8EXojlIBSK7PHHNxpW9AL0tzJQ5h/xp9IauABJGQuxFfCDAOYiX1yep8BQSVQBo7RlwuVICsIVhjcy3uipdKDZ2B1bKZ1nCUT16KwW9JXFWZzKJ0/afeqIwG0GnaIp72FYr/KEjAGSIKvN9uVVY1fEMeRoN9+PIqr/MMOyxuu5+8ZGY1JtKY4+1Xcv0ubCWpIpssHwUoS7JPjfaS6k+pn+8XscL0Ve9nutKCj1vQOgGbJTXDtweswvz8F3zlArEVlOBK71fDaH0vMPp0tB8sggAcnwbs=

cache:
  directories:
  - "$HOME/.m2"

script:
- mvn clean install

after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker push shboland/discovery-service
